// Freecurrency API supported currencies
// https://freecurrencyapi.com/docs/currency-list
export enum Currency {
  EUR = "EUR",
  USD = "USD",
  JPY = "JPY",
  BGN = "BGN",
  CZK = "CZK",
  DKK = "DKK",
  GBP = "GBP",
  HUF = "HUF",
  PLN = "PLN",
  RON = "RON",
  SEK = "SEK",
  CHF = "CHF",
  ISK = "ISK",
  NOK = "NOK",
  HRK = "HRK",
  RUB = "RUB",
  TRY = "TRY",
  AUD = "AUD",
  BRL = "BRL",
  CAD = "CAD",
  CNY = "CNY",
  HKD = "HKD",
  IDR = "IDR",
  ILS = "ILS",
  INR = "INR",
  KRW = "KRW",
  MXN = "MXN",
  MYR = "MYR",
  NZD = "NZD",
  PHP = "PHP",
  SGD = "SGD",
  THB = "THB",
  ZAR = "ZAR",
}

export const currencySymbols: { [key in Currency]: string } = {
  EUR: "€",
  USD: "$",
  JPY: "¥",
  BGN: "лв",
  CZK: "Kč",
  DKK: "kr",
  GBP: "£",
  HUF: "Ft",
  PLN: "zł",
  RON: "lei",
  SEK: "kr",
  CHF: "CHF",
  ISK: "kr",
  NOK: "kr",
  HRK: "kn",
  RUB: "₽",
  TRY: "₺",
  AUD: "$",
  BRL: "R$",
  CAD: "$",
  CNY: "¥",
  HKD: "HK$",
  IDR: "Rp",
  ILS: "₪",
  INR: "₹",
  KRW: "₩",
  MXN: "$",
  MYR: "RM",
  NZD: "$",
  PHP: "₱",
  SGD: "S$",
  THB: "฿",
  ZAR: "R",
};
